export const TaskData = {
  userName: "Anima Agrawal",
  location: "UP, India",
  tasks: [
    {
      id: 1,
      status: "todo",
      priority: "Low",
      title: "Brainstorming",
      description:
        "Brainstorming brings team members' diverse experience into play. ",
      comments: 12,
      files: 0,
      photos:[],
      guests: [
        "https://www.shutterstock.com/image-vector/simple-cartoon-avatar-vector-flat-260nw-1988123576.jpg",
        "https://www.persofoto.de/apple-touch-icon-180x180.png",
        "https://www.shutterstock.com/image-vector/simple-cartoon-girl-avatar-drawing-600w-1988228618.jpg",
      ],
    },
    {
      id: 2,
      status: "todo",
      priority: "High",
      title: "Research",
      description:
        "User research helps you to create an optimal product for users.",
      comments: 10,
      files: 3,
      photos:[],
      guests: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxcryDQUGWA6r5cfwJtfIo6ylDVf97EUGoIhokfp5Mbdlaocg4GElk9NSYfdKHMQrlu5w&usqp=CAU",
        "https://www.shutterstock.com/image-vector/simple-cartoon-girl-avatar-drawing-600w-1988228618.jpg",
        "https://cdn5.vectorstock.com/i/1000x1000/17/84/cute-young-man-avatar-character-cartoon-style-vector-36211784.jpg",
      ],
    },
    {
      id: 3,
      status: "todo",
      priority: "High",
      title: "Wireframes",
      description:
        "Low fidelity wireframes include the most basic content and visuals.",
      comments: 2,
      files: 0,
      photos:[],
      guests: [
        "https://assets2.lottiefiles.com/avatars/300_20577-489096009.jpg",
        "https://cdn-icons-png.flaticon.com/512/3898/3898816.png",
        "https://clipart-library.com/data_images/122649.png",
      ],
    },
    {
      id: 4,
      status: "onprogress",
      priority: "Low",
      title: "Onboarding Illustrations ",
      description: "",
      photos: ["https://cdn.pixabay.com/photo/2013/07/21/13/00/rose-165819_640.jpg"],
      comments: 14,
      files: 15,
      guests: [
        "https://cdn1.vectorstock.com/i/1000x1000/20/60/cute-beautiful-girl-avatar-character-young-woman-vector-35992060.jpg",
        "https://assets2.lottiefiles.com/avatars/300_20577-489096009.jpg",
      ],
    },
    {
      id: 5,
      status: "onprogress",
      priority: "Low",
      title: "Moodboard",
      description: "",
      photos: ["https://wallpaperaccess.com/full/420120.jpg", "https://images5.alphacoders.com/344/344761.jpg"],
      comments: 9,
      files: 10,
      guests: [
        "https://clipart-library.com/data_images/122649.png",
        "https://cdn5.vectorstock.com/i/1000x1000/17/84/cute-young-man-avatar-character-cartoon-style-vector-36211784.jpg",
      ],
    },
    {
      id: 6,
      status: "done",
      priority: "Low",
      title: "Mobile App Design",
      description: "",
      comments: 12,
      photos: ["https://cdn.pixabay.com/photo/2015/04/19/08/32/marguerite-729510_1280.jpg"],
      files: 15,
      guests: [
        "https://cdn-icons-png.flaticon.com/512/3898/3898816.png",
        "https://cdn5.vectorstock.com/i/1000x1000/17/84/cute-young-man-avatar-character-cartoon-style-vector-36211784.jpg",
      ],
    },
    {
      id: 7,
      status: "done",
      priority: "Low",
      title: "Design System",
      description: "It just needs to adapt the UI from what you did before.",
      comments: 12,
      files: 15,
      guests: [
        "https://assets2.lottiefiles.com/avatars/300_20577-489096009.jpg",
        "https://cdn-icons-png.flaticon.com/512/3898/3898816.png",
        "https://clipart-library.com/data_images/122649.png",
      ],
    },
  ],
};
